export default {
  'Search': 'Search',
  'Difficulty': 'Difficulty',
  'Question': 'Question',
  'Questions': 'Questions',
  'Status': 'Status',
  'Tags': 'Tags',
  'Date': 'Date',
  'New Question': 'New Question',
  'Rows Per Page': 'Rows Per Page',
  'edit': 'edit',
  'Delete': 'Delete',
  'Reject': 'Reject',
  "Approve": "Approve",
  'TAG': 'TAG',
  'Close': 'Close',
  'SAVE &amp; ADD NEW QUESTION': 'SAVE & ADD NEW QUESTION',
  'Add New Answer': 'Add New Answer',
  'Answer': 'Answer',
  'Add Tag': 'Add Tag',
  'SAVE': 'SAVE',
}