export default {
  'Search': 'Arama',
  'Difficulty': 'Zorluk',
  'Question': 'Soru',
  'Questions': 'Sorular',
  'Status': 'Durum',
  'Tags': 'Etiketler',
  'Date': 'Tarih',
  'New Question': 'Yeni Soru',
  'Rows Per Page': 'Sayfa Başına Satır',
  'edit': 'Düzenle',
  'Delete': 'Silmek',
  'Reject': 'Reddetmek',
  "Approve": "Onaylamak",
  'TAG': 'Etiket',
  'Close': 'Kapat',
  'SAVE &amp; ADD NEW QUESTION': 'KAYDET VE YENİ SORU EKLE',
  'Add New Answer': 'Yeni Yanıt Ekle',
  'Answer': 'Cevap',
  'Add Tag': 'Etiket Ekle',
  'SAVE': 'KAYIT ETMEK',
}